title: kdougan, a blog
email: kdougan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An awesome description
baseurl: /blog
url: 'kdougan.com'
twitter_username: f0ursqu4r3
github_username: kdougan

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed

highlighter: rouge

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title/

paginate: 5
paginate_path: /posts/:num
